version: "3.8"

services:

  frontend:
    build: .
    volumes:
      - "./src:/app/src:ro"
      - "./public:/app/public:ro"
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: yarn start
